### ISSUE TITLE
crash on test when using Parcelable in the PlaybackState

### ISSUE THREAD

**Issue by dpreussler** [googlesamples/android-media-controller#32]
the app crashes when trying to print a bundle that contains Parcelables from the other app as they cant be loaded

```
07-29 13:49:02.056 26327 26327 E Parcel  : Class not found when unmarshalling: com.xxx.yyy.zzz.TrackSourceInfo
07-29 13:49:02.056 26327 26327 E Parcel  : java.lang.ClassNotFoundException: com.xxx.yyy.zzz.TrackSourceInfo
07-29 13:49:02.056 26327 26327 E Parcel  : 	at java.lang.Class.classForName(Native Method)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at java.lang.Class.forName(Class.java:454)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3338)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:3272)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:3174)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.BaseBundle.keySet(BaseBundle.java:569)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at com.example.android.mediacontroller.TestUtilsKt.formatPlaybackStateExtras(TestUtils.kt:229)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at com.example.android.mediacontroller.TestUtilsKt.formatPlaybackState(TestUtils.kt:269)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at com.example.android.mediacontroller.MediaAppTestingActivity$controllerCallback$1.onPlaybackStateChanged(MediaAppTestingActivity.kt:1127)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.support.v4.media.session.MediaControllerCompat$Callback$MessageHandler.handleMessage(MediaControllerCompat.java:1084)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.os.Looper.loop(Looper.java:223)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at android.app.ActivityThread.main(ActivityThread.java:7664)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at java.lang.reflect.Method.invoke(Native Method)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-29 13:49:02.056 26327 26327 E Parcel  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by romanofranz** [comment]
Thanks @dpreussler !

**Comment by psychoticbeef** [comment]
@dpreussler @romanofranz It seems the crash also happens when other fields contain parcelable data:

`11-05 12:42:04.945 11329 11329 I MediaAppTestingActivity: <Metadata>
11-05 12:42:04.945 11329 11329 I MediaAppTestingActivity: USER_RATING:         Rating
11-05 12:42:04.945 11329 11329 I MediaAppTestingActivity: DISPLAY_TITLE:       REDACTED
11-05 12:42:04.945 11329 11329 I MediaAppTestingActivity: MEDIA_ID:            REDACTED
11-05 12:42:04.945 11329 11329 I MediaAppTestingActivity: DISPLAY_ICON_URI:    REDACTED
11-05 12:42:04.945 11329 11329 I MediaAppTestingActivity: METADATA_KEY_REDACTED.media.metadata.REDACTED: REDACTED
11-05 12:42:04.948 11329 11329 I MediaAppTestingActivity: <Repeat Mode>
11-05 12:42:04.948 11329 11329 I MediaAppTestingActivity: NONE
11-05 12:42:04.950 11329 11329 I MediaAppTestingActivity: <Shuffle Mode>
11-05 12:42:04.950 11329 11329 I MediaAppTestingActivity: NONE
11-05 12:42:04.951 11329 11329 I MediaAppTestingActivity: <Queue Title>
11-05 12:42:04.951 11329 11329 I MediaAppTestingActivity: null
11-05 12:42:04.968 11329 11329 E Parcel  : Class not found when unmarshalling: -NAME REDACTED-
11-05 12:42:04.968 11329 11329 E Parcel  : java.lang.ClassNotFoundException: -NAME REDACTED-
11-05 12:42:04.968 11329 11329 E Parcel  :  at java.lang.Class.classForName(Native Method)
11-05 12:42:04.968 11329 11329 E Parcel  :  at java.lang.Class.forName(Class.java:454)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Parcel.readParcelableCreator(Parcel.java:3338)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Parcel.readParcelable(Parcel.java:3272)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Parcel.readValue(Parcel.java:3174)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.BaseBundle.unparcel(BaseBundle.java:236)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Bundle.getParcelable(Bundle.java:1001)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.MediaDescriptionCompat.fromMediaDescription(MediaDescriptionCompat.java:387)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.session.MediaSessionCompat$QueueItem.fromQueueItem(MediaSessionCompat.java:1848)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.session.MediaSessionCompat$QueueItem.fromQueueItemList(MediaSessionCompat.java:1870)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.session.MediaControllerCompat$MediaControllerImplApi21.getQueue(MediaControllerCompat.java:2048)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.session.MediaControllerCompat.getQueue(MediaControllerCompat.java:343)
11-05 12:42:04.968 11329 11329 E Parcel  :  at com.example.android.mediacontroller.MediaAppTestingActivity.logCurrentController(MediaAppTestingActivity.kt:1117)
11-05 12:42:04.968 11329 11329 E Parcel  :  at com.example.android.mediacontroller.MediaAppTestingActivity.setupMediaController(MediaAppTestingActivity.kt:427)
11-05 12:42:04.968 11329 11329 E Parcel  :  at com.example.android.mediacontroller.MediaAppTestingActivity.access$setupMediaController(MediaAppTestingActivity.kt:100)
11-05 12:42:04.968 11329 11329 E Parcel  :  at com.example.android.mediacontroller.MediaAppTestingActivity$setupMedia$1.onConnected(MediaAppTestingActivity.kt:362)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.MediaBrowserCompat$ConnectionCallback$StubApi21.onConnected(MediaBrowserCompat.java:669)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.support.v4.media.MediaBrowserCompatApi21$ConnectionCallbackProxy.onConnected(MediaBrowserCompatApi21.java:103)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.media.browse.MediaBrowser$6.run(MediaBrowser.java:603)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Handler.handleCallback(Handler.java:938)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Handler.dispatchMessage(Handler.java:99)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.os.Looper.loop(Looper.java:223)
11-05 12:42:04.968 11329 11329 E Parcel  :  at android.app.ActivityThread.main(ActivityThread.java:7664)
11-05 12:42:04.968 11329 11329 E Parcel  :  at java.lang.reflect.Method.invoke(Native Method)
11-05 12:42:04.968 11329 11329 E Parcel  :  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-05 12:42:04.968 11329 11329 E Parcel  :  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-05 12:42:04.968 11329 11329 E Parcel  : Caused by: java.lang.ClassNotFoundException: Didn't find class "-NAME REDACTED-" on path: DexPathList[[zip file "/data/app/~~YTYnPkBBaYfEuYGzp92MbQ==/com.example.android.mediacontroller-ALCEfH9YsFh3W74a78JFpA==/base.apk"],nativeLibraryDirectories=[/data/app/~~YTYnPkBBaYfEuYGzp92MbQ==/com.example.android.mediacontroller-ALCEfH9YsFh3W74a78JFpA==/lib/x86_64, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
11-05 12:42:04.968 11329 11329 E Parcel  :  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
11-05 12:42:04.968 11329 11329 E Parcel  :  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-05 12:42:04.968 11329 11329 E Parcel  :  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-05 12:42:04.968 11329 11329 E Parcel  :  ... 28 more`
